version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
